# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celulas',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nomcelula', models.CharField(max_length=2000, verbose_name='nombre')),
                ('barrio', models.CharField(max_length=2000)),
                ('diacelula', models.CharField(max_length=2000)),
                ('lugar', models.CharField(max_length=2000)),
                ('estado_celula', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_galeria', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='galeria')),
                ('nombre_imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cedula Identidad')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=200, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=15, verbose_name='telefono')),
                ('barrio', models.CharField(max_length=2000, verbose_name='Barrio')),
                ('e_civil', models.CharField(max_length=2000, verbose_name='Estado Civil')),
                ('f_nac', models.DateField()),
                ('estado', models.BooleanField()),
                ('genero', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='celulas',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iglesia.Persona'),
        ),
    ]
